### ISSUE TITLE
Upgrade to jackson 2.12.1 [PAXLOGGING-318]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.logging#380]
**[Jean-Baptiste Onofre](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:ceaddc8e-afbf-4078-a7c0-089234224087)** created **[PAXLOGGING-318](https://ops4j1.jira.com/browse/PAXLOGGING-318)** 

---

Votes: 0, Watches: 1

**Comment by grgrzybek** [comment]
It's only a test dependency. I'll update anyway, but it's worth noting.
