### ISSUE TITLE
Log4jv2LoggerContextFactory incompatible with upstream

### ISSUE THREAD

**Issue by brevilo** [ops4j/org.ops4j.pax.logging#395]
[`Log4jv2LoggerContextFactory`](https://github.com/ops4j/org.ops4j.pax.logging/blob/master/pax-logging-api/src/main/java/org/ops4j/pax/logging/log4jv2/Log4jv2LoggerContextFactory.java#L33) lacks the implementation of upstream's `ShutdownCallbackRegistry` interface, [introduced](https://github.com/apache/logging-log4j2/commit/cd5edee067cb577d9d2f7607af41bf1f99da0a60) in Log4j2 2.1 (back in 2014).

This leads to an incompatibility with upstream's [JeroMqAppender](https://github.com/apache/logging-log4j2/commit/a6af67c5d6faee5b4d422add674e4c518c33d528) which requires that interface's implementation as of Log4j2 2.6. Trying to use it via pax-logging currently triggers a [`ClassCastException`](https://github.com/apache/logging-log4j2/commit/a6af67c5d6faee5b4d422add674e4c518c33d528#diff-3c45e4089b872df05f9678343175c5140c08e421d3369b3a8764ef6cdda19026R98).

Since JeroMqAppender is one of the few remaining core appenders (until Log4j 3.0 or availability of the currently missing modularized appenders) for remote log targets it would be great to see this fixed.

Thanks!

**Comment by grgrzybek** [comment]
Thanks for reporting!
I tried several approaches, but eventually I ended with https://issues.apache.org/jira/browse/LOG4J2-3040 - please check the details there and if possibly, add your own comments @brevilo .

If log4j2 team decides to move `ShutdownCallbackRegistry` interface to log4j-api, I have ready implementation which calls the shutdown hooks when pax-logging-api bundle is stopped (that's ideal OSGi solution), but I suggested other solutions to this ClassCastException as well.

**Comment by brevilo** [comment]
Nice one, thanks for trying! Hopefully upstream takes this one up.

**Comment by jbonofre** [comment]
As LOG4J2-3040 is not yet fixed, I'm postponing this issue to 2.0.11.

**Comment by grgrzybek** [comment]
https://issues.apache.org/jira/browse/LOG4J2-3040 is still not resolved...
