### ISSUE TITLE
NoSuchMethod exception thrown when constructing the Apache Commons LogFactoryImpl

### ISSUE THREAD

**Issue by pjs102** [ops4j/org.ops4j.pax.logging#400]
Constructing a new instance of the LogFactoryImpl() from the apache-commons-logging api, results in a No Such Method Error being thrown for the LogFactory.getClassLoader() .  This is because the LogFactory class has been overriden, but has not been kept up-to-date with the revision that is being patched.

Attached is a unit test that shows the problem.
       @Test
	public void testLogFactoryImpl() {
		LogFactoryImpl factory = new LogFactoryImpl();
		Log logger = factory.getInstance(LogFactoryImplTest.class);
		logger.info("Hello World");
	}

Which results in the following stack-trace. 

java.lang.NoSuchMethodError: org.apache.commons.logging.LogFactory.getClassLoader(Ljava/lang/Class;)Ljava/lang/ClassLoader;
	at org.apache.commons.logging.impl.LogFactoryImpl.getClassLoader(LogFactoryImpl.java:392)
	at org.apache.commons.logging.impl.LogFactoryImpl.initDiagnostics(LogFactoryImpl.java:420)
	at org.apache.commons.logging.impl.LogFactoryImpl.<init>(LogFactoryImpl.java:87)
	at org.apache.commons.logging.LogFactoryImplTest.testLogFactoryImpl(LogFactoryImplTest.java:11)

**Comment by grgrzybek** [comment]
`org.apache.commons.logging.impl.LogFactoryImpl` is the default implementation of `org.apache.commons.logging.LogFactory` interface used as a fallback (`org.apache.commons.logging.LogFactory#FACTORY_DEFAULT`) after all discovery methods fail.

The normal (non-OSGi) discovery process (`static org.apache.commons.logging.LogFactory#getFactory()`) is:
1. cached factory attached to TCCL
2. `org.apache.commons.logging.LogFactory` system property
3. `META-INF/services/org.apache.commons.logging.LogFactory` service
4. `org.apache.commons.logging.LogFactory` property from `commons-logging.properties`
5. Instantiate the fallback/default `org.apache.commons.logging.impl.LogFactoryImpl`

Pax Logging overrides the public, static `org.apache.commons.logging.LogFactory#getFactory()` method (by overriding, I mean it changes it completely), so it **always** returns a singleton instance of `org.apache.commons.logging.LogFactory` - the factory itself.

Mind that `org.apache.commons.logging.LogFactory` is abstract in commons-logging-1.2.jar and it's concrete in pax-logging.

There was absolutely no need to instantiate `org.apache.commons.logging.impl.LogFactoryImpl`. Never.

Please tell me - why would you even want to instantiate the `LogFactoryImpl`?

**Comment by pjs102** [comment]
Hello.

Some of our older applications use third party apache projects.  These in turn the commons-discovery service to locate the commons-logging LogFactory.  This discovery process is the thing that is instantiating the LogFactoryImpl, rather than LogFactory.

The reason for getting the Method Not Found Exception is that PAX has patched version 1.0 of the LogFactory class, but the project is now bringing in 1.2.

Please can you update the LogFactory class with the protected methods from version 1.2.

Thanks
Paul

**Comment by grgrzybek** [comment]
I see. I never planned to synchronize non-public methods... BTW - did you try to patch this locally and check if it works?

**Comment by pjs102** [comment]
Yes, I have tried a local patch to fix the "method not found" exception.  This worked, but it is not backed by the PaxLoggingManager.

**Comment by grgrzybek** [comment]
But removing "method not found" solves your problem anyway, right? :)

**Comment by pjs102** [comment]
Yes that did solve my problem for now. :-)

**Comment by grgrzybek** [comment]
@pjs102 Fixed in 1.11.x and 2.0.x. We can have a release soon.
