### ISSUE TITLE
How to configure to support Apache skywalking

### ISSUE THREAD

**Issue by duan2ping** [ops4j/org.ops4j.pax.logging#409]
How to configure pax-logging to use Apache skywalking in karaf?

**Comment by duan2ping** [comment]
@grgrzybek Thanks for your answer.
I need to modify the layout of Pax Logging to the layout of Skywalking extension. If the Skywalking layout is converted to Pax Logging layout by customizing the layout, it may be a bit troublesome. Is there any way to use Skywalking layout directly?

**Comment by grgrzybek** [comment]
Hmm, I'd need more information - first - is Skywalking OSGi-aware at all?
By layout you mean the format of messages of the logging events? Or simply the format of the lines written to stdout/file?

Pax Logging doesn't assume any _layout_ (though there are default layouts of Logback/Log4j1/Log4j2)...
What is the Skywalking layout?

**Comment by duan2ping** [comment]
Hi!
I am afraid that Skywalking does not support OSGi. (https://github.com/apache/skywalking/discussions/7959)

Yes, it is the message format. As shown below, I need to change "log4j2.appender.console.layout.type" to TraceIdPatternLayout of Skywalking extension.

Configuration file of Karaf: org.ops4j.pax.logging.cfg
Configuration content:
--------
log4j2.appender.console.type = Console
log4j2.appender.console.name = Console
log4j2.appender.console.layout.type = PatternLayout
log4j2.appender.console.layout.pattern = ${log4j2.out.pattern}
--------

**Comment by grgrzybek** [comment]
I tried googling `TraceIdPatternLayout` and I found https://github.com/apache/skywalking/blob/c467e4df06cefd5914082ed8cc093d538dc42e2c/test/e2e-v2/java-test-service/e2e-service-provider/src/main/resources/log4j.properties

However it's for Log4j1...

pax.logging (both for log4j1 and log4j2) has fragment samples where you (in theory) could implement any kind of extension. For example, [this is a sample `List` appender](https://github.com/ops4j/org.ops4j.pax.logging/blob/main/pax-logging-samples/fragment-log4j2/src/main/java/org/ops4j/pax/logging/log4j2/extra/ListAppender.java) which can be configured like this:
```
builtin.list.log4j2.appender.l.type = List
builtin.list.log4j2.appender.l.name = l
```

I believe you can create your own layout as well...

Remember that _layout_ is only an event → message converted and I think Skywalking needs some kind of appender to tunnel events from the logging framework to Skywalking itself...

**Comment by duan2ping** [comment]
Okay, thank you very much! let me give it a try.

I'm sorry, TraceIdPatternLayout is the layout of Skywalking extension log4j1, but my example is log4j2.
[Skywalking-Log4j2](https://skywalking.apache.org/docs/main/v8.6.0/en/setup/service-agent/java-agent/application-toolkit-log4j-2.x/) This is how Skywalking is configured in log4j2.

**Comment by grgrzybek** [comment]
At first glance, after checking https://github.com/apache/skywalking-java/blob/e6447d517558031f49cc4450467e41b644320071/apm-application-toolkit/apm-toolkit-log4j-2.x/src/main/java/org/apache/skywalking/apm/toolkit/log/log4j/v2/x/TraceIdConverter.java I see this JAR is a log4j2 plugin (see its `META-INF/org/apache/logging/log4j/core/config/plugins/Log4j2Plugins.dat`).

So you'd have to turn this plugin into a fragment bundle for pax-logging-log4j2 the same way as https://github.com/ops4j/org.ops4j.pax.logging/blob/main/pax-logging-samples/fragment-log4j2/pom.xml is a Log4j2 plugin and OSGi fragment, while the POM uses:
```xml
<annotationProcessor>org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor</annotationProcessor>
```

**Comment by duan2ping** [comment]
Thank you very much! let me give it a try.

**Comment by grgrzybek** [comment]
any news @duan2ping ?

**Comment by grgrzybek** [comment]
any news about this issue @duan2ping ?

**Comment by duan2ping** [comment]
I'm very sorry, due to some work changes, I haven't tried again. Thank you very much for your help.
