### ISSUE TITLE
Upgrade log4j2 at least to 2.15.0

### ISSUE THREAD

**Issue by kaikreuzer** [ops4j/org.ops4j.pax.logging#415]
There's a critical CVE published for any log4j2 version <2.15.0, see https://github.com/advisories/GHSA-jfh8-c2jp-5v3q.

In order to not put any downstream projects of PAX Logging at risk, a new version should be published asap.

**Comment by Flole998** [comment]
Apparently this was fixed in #413 about 4 hours ago and there is already planning for a new release going on if I look at the last commits.

**Comment by grgrzybek** [comment]
Thanks for reporting - thanks to my Japanese friends, I was able to start tackling it very soon. The releases are ready:
* https://repo1.maven.org/maven2/org/ops4j/pax/logging/1.11.9/
* https://repo1.maven.org/maven2/org/ops4j/pax/logging/2.0.11/

Duplicate of #413

**Comment by kaikreuzer** [comment]
Wow, that was quick - thanks, guys!
