### ISSUE TITLE
[2.x] Removing log4j1 dependency from pax-logging

### ISSUE THREAD

**Issue by tharindu1st** [ops4j/org.ops4j.pax.logging#436]
In current pax-logging dependencies, it packs the log4j1 related dependencies inside in jar.
Since log4j1 retired in 2015 as per [1], Is there any plan to release a new pax-logging version, removing the log4j1 related dependencies?.
[1] - https://logging.apache.org/log4j/1.2/

**Comment by grgrzybek** [comment]
Hmm, it's worth considering in next minor (2.1) or major (3.0) release.

**Comment by tharindu1st** [comment]
Hi @grgrzybek,
Thanks for the update.

**Comment by tharindu1st** [comment]
Hi @grgrzybek,

Will it be possible to get a release in the 1.x range for this same ?.

Thanks.
Tharindu.

**Comment by grgrzybek** [comment]
For compatibility reasons, I don't think we can remove pax-logging-service from 1.1.x (pax-logging-log4j1 in 2.0.x)...

WDYT @jbonofre , @gnodet , @ffang ?

**Comment by tharindu1st** [comment]
Hi @grgrzybek 
Is there any timeline on releasing the pax-logging 2.1 or 3.0 release?

**Comment by grgrzybek** [comment]
As mentioned in #410, R8 doesn't introduce any important changes except some clarification. I think we can release 2.1.0 in January and it's a good opportunity to remove `pax-logging-service` (`pax-logging-log4j1`) bundle entirely.
Mind that I'm NOT going to remove Log4j1 API from pax-logging-api - I'm only going to remove the implementation of Pax Logging based on Log4j1.

**Comment by tharindu1st** [comment]
Hi @grgrzybek
Will it remove log4j1 references from the **pax-logging-api** jar from the next major release?.

**Comment by grgrzybek** [comment]
@tharindu1st nope ;) log4j1 has API and Implementation. I've completely removed the implementation and left only the API which still has to be used. It's safe. Really. No CVEs. Ever ;)

**Comment by grgrzybek** [comment]
And Maven `log4j:log4j` dependency was switched to `ch.qos.reload4j:reload4j` here: https://github.com/ops4j/org.ops4j.pax.logging/commit/f91a56757b5f263887ad7ab9db70e16fce9facdc
