### ISSUE TITLE
Error try to compile pax-logging-log4j2

### ISSUE THREAD

**Issue by melkorex** [ops4j/org.ops4j.pax.logging#437]
Hi guys i download org.ops4j.pax.logging-main.zip file.
Unzip file in my eclipse workspace.
Load folder in eclipse.
Build with maven pax-logging-log4j2 -> clean install o clean compile.
And eclipse throw me an error...

`Could not resolve dependencies for project org.ops4j.pax.logging:pax-logging-log4j2:bundle:2.0.15-SNAPSHOT: Failed to collect dependencies at org.ops4j.pax.logging:pax-logging-api:jar:2.0.15-SNAPSHOT: Failed to read artifact descriptor for org.ops4j.pax.logging:pax-logging-api:jar:2.0.15-SNAPSHOT: org.ops4j.pax:logging:pom:2.0.15-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]`

You know how fix it? i need pax-logging-log4j2 with log4j 2.17.1

**Comment by melkorex** [comment]
Download 2.0.14 from releases.
mvn clean install
`[INFO] Scanning for projects...
[INFO] Inspecting build with total of 18 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 18 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] OPS4J Pax Logging (Build POM)                                      [pom]
[INFO] OPS4J Pax Logging - API                                         [bundle]
[INFO] OPS4J Pax Logging - API tests                                      [jar]
[INFO] OPS4J Pax Logging - Log4Jv1 implementation                      [bundle]
[INFO] OPS4J Pax Logging - Log4Jv2 implementation                      [bundle]
[INFO] OPS4J Pax Logging - Log4Jv2 extra packages                      [bundle]
[INFO] OPS4J Pax Logging - Logback implementation                      [bundle]
[INFO] OPS4J Pax Logging - Samples (Build POM)                            [pom]
[INFO] OPS4J Pax Logging - Samples - Fragment                          [bundle]
[INFO] OPS4J Pax Logging - Samples - Fragment for Logback              [bundle]
[INFO] OPS4J Pax Logging - Samples - Fragment for Log4J2               [bundle]
[INFO] OPS4J Pax Logging - Samples - Fragment for Log4J2/H2            [bundle]
[INFO] OPS4J Pax Logging - Integration Tests                              [jar]
[INFO] OPS4J Pax Logging - Karaf                                          [pom]
[INFO] OPS4J Pax Logging - Karaf KAR Logger                            [bundle]
[INFO] OPS4J Pax Logging - Karaf KAR                                      [pom]
[INFO] OPS4J Pax Logging - Karaf Distribution                             [pom]
[INFO] OPS4J Pax Logging - Karaf Integration Tests                        [jar]
[INFO]
[INFO] -----------------------< org.ops4j.pax:logging >------------------------
[INFO] Building OPS4J Pax Logging (Build POM) 2.0.14                     [1/18]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ logging ---
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-maven) @ logging ---
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ logging ---
[INFO] Installing C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pom.xml to C:\Users\AlejandroMarceloGaff\.m2\repository\org\ops4j\pax\logging\2.0.14\logging-2.0.14.pom
[INFO]
[INFO] ---------------< org.ops4j.pax.logging:pax-logging-api >----------------
[INFO] Building OPS4J Pax Logging - API 2.0.14                           [2/18]
[INFO] -------------------------------[ bundle ]-------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ pax-logging-api ---
[INFO] Deleting C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api\target
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-maven) @ pax-logging-api ---
[INFO]
[INFO] --- maven-dependency-plugin:3.1.1:unpack (unpack-log4j-api) @ pax-logging-api ---
[INFO] Configured Artifact: org.apache.logging.log4j:log4j-api:?:jar
[INFO] Unpacking C:\Users\AlejandroMarceloGaff\.m2\repository\org\apache\logging\log4j\log4j-api\2.17.1\log4j-api-2.17.1.jar to C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api\target\unpack-deps\log4j-api with includes "" and excludes ""
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ pax-logging-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-selected-packages) @ pax-logging-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ pax-logging-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 88 source files to C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api\target\classes
[INFO] /C:/eclipse/java/workspace/org.ops4j.pax.logging-logging-2.0.14/pax-logging-api/src/main/java/org/ops4j/pax/logging/spi/support/LogEntryImpl.java: Some input files use or override a deprecated API.
[INFO] /C:/eclipse/java/workspace/org.ops4j.pax.logging-logging-2.0.14/pax-logging-api/src/main/java/org/ops4j/pax/logging/spi/support/LogEntryImpl.java: Recompile with -Xlint:deprecation for details.
[INFO] /C:/eclipse/java/workspace/org.ops4j.pax.logging-logging-2.0.14/pax-logging-api/src/main/java/org/ops4j/pax/logging/spi/support/OsgiUtil.java: Some input files use or override a deprecated API that is marked for removal.
[INFO] /C:/eclipse/java/workspace/org.ops4j.pax.logging-logging-2.0.14/pax-logging-api/src/main/java/org/ops4j/pax/logging/spi/support/OsgiUtil.java: Recompile with -Xlint:removal for details.
[INFO] /C:/eclipse/java/workspace/org.ops4j.pax.logging-logging-2.0.14/pax-logging-api/src/main/java/org/ops4j/pax/logging/slf4j/Slf4jMDCAdapter.java: Some input files use unchecked or unsafe operations.
[INFO] /C:/eclipse/java/workspace/org.ops4j.pax.logging-logging-2.0.14/pax-logging-api/src/main/java/org/ops4j/pax/logging/slf4j/Slf4jMDCAdapter.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ pax-logging-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ pax-logging-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api\target\test-classes
[INFO] /C:/eclipse/java/workspace/org.ops4j.pax.logging-logging-2.0.14/pax-logging-api/src/test/java/org/ops4j/pax/logging/spi/support/FormattingTripleTest.java: C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api\src\test\java\org\ops4j\pax\logging\spi\support\FormattingTripleTest.java uses or overrides a deprecated API.
[INFO] /C:/eclipse/java/workspace/org.ops4j.pax.logging-logging-2.0.14/pax-logging-api/src/test/java/org/ops4j/pax/logging/spi/support/FormattingTripleTest.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ pax-logging-api ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.log4j.MDCTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.06 s - in org.apache.log4j.MDCTest
[INFO] Running org.ops4j.pax.logging.internal.JdkHandlerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.653 s - in org.ops4j.pax.logging.internal.JdkHandlerTest
[INFO] Running org.ops4j.pax.logging.spi.support.FormattingTripleTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 s - in org.ops4j.pax.logging.spi.support.FormattingTripleTest
[INFO] Running org.ops4j.pax.logging.spi.support.LogReaderTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.ops4j.pax.logging.spi.support.LogReaderTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-bundle-plugin:5.1.2:bundle (default-bundle) @ pax-logging-api ---
[WARNING] Bundle org.ops4j.pax.logging:pax-logging-api:bundle:2.0.14 : Version for package org.apache.juli.logging is set to different values in the source (9.0.27) and in the manifest (9.0.43). The version in the manifest is not picked up by an other sibling bundles in this project or projects that directly depend on this project
[WARNING] Bundle org.ops4j.pax.logging:pax-logging-api:bundle:2.0.14 : Export org.apache.logging.log4j.spi,  has 1,  private references [org.apache.logging.log4j.internal]
[WARNING] Bundle org.ops4j.pax.logging:pax-logging-api:bundle:2.0.14 : Classes found in the wrong directory: {META-INF/versions/9/org/apache/logging/log4j/util/StackLocator.class=org.apache.logging.log4j.util.StackLocator, META-INF/versions/9/module-info.class=module-info, META-INF/versions/9/org/apache/logging/log4j/util/internal/DefaultObjectInputFilter.class=org.apache.logging.log4j.util.internal.DefaultObjectInputFilter, META-INF/versions/9/org/apache/logging/log4j/util/Base64Util.class=org.apache.logging.log4j.util.Base64Util, META-INF/versions/9/org/apache/logging/log4j/util/ProcessIdUtil.class=org.apache.logging.log4j.util.ProcessIdUtil}
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ pax-logging-api ---
[INFO] Installing C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api\target\pax-logging-api-2.0.14.jar to C:\Users\AlejandroMarceloGaff\.m2\repository\org\ops4j\pax\logging\pax-logging-api\2.0.14\pax-logging-api-2.0.14.jar
[INFO] Installing C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api\pom.xml to C:\Users\AlejandroMarceloGaff\.m2\repository\org\ops4j\pax\logging\pax-logging-api\2.0.14\pax-logging-api-2.0.14.pom
[INFO]
[INFO] --- maven-bundle-plugin:5.1.2:install (default-install) @ pax-logging-api ---
[INFO] Local OBR update disabled (enable with -DobrRepository)
[INFO]
[INFO] -------------< org.ops4j.pax.logging:pax-logging-api-test >-------------
[INFO] Building OPS4J Pax Logging - API tests 2.0.14                     [3/18]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ pax-logging-api-test ---
[INFO] Deleting C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-maven) @ pax-logging-api-test ---
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ pax-logging-api-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ pax-logging-api-test ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ pax-logging-api-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ pax-logging-api-test ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ pax-logging-api-test ---
[INFO] No tests to run.
[INFO]
[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ pax-logging-api-test ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] Building jar: C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\pax-logging-api-test-2.0.14.jar
[INFO]
[INFO] --- maven-invoker-plugin:3.2.2:install (integration-test) @ pax-logging-api-test ---
[INFO] Installing C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pom.xml to C:\Users\AlejandroMarceloGaff\.m2\repository\org\ops4j\pax\logging\2.0.14\logging-2.0.14.pom
[INFO] Installing C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\pom.xml to C:\Users\AlejandroMarceloGaff\.m2\repository\org\ops4j\pax\logging\pax-logging-api-test\2.0.14\pax-logging-api-test-2.0.14.pom
[INFO] Installing C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\pax-logging-api-test-2.0.14.jar to C:\Users\AlejandroMarceloGaff\.m2\repository\org\ops4j\pax\logging\pax-logging-api-test\2.0.14\pax-logging-api-test-2.0.14.jar
[INFO]
[INFO] --- maven-invoker-plugin:3.2.2:run (integration-test) @ pax-logging-api-test ---
[INFO] Building: jboss-logging\pom.xml
[INFO] run post-build script verify.groovy
[INFO]   java.io.FileNotFoundException: C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\jboss-logging\target\surefire-reports\org.ops4j.pax.logging.test.jbosslogging.JBossLoggingNativeApiTest-output.txt (El sistema no puede encontrar la ruta especificada)
[INFO]           jboss-logging\pom.xml ............................ FAILED (1.7 s)
[INFO] Building: jcl-without-impl\pom.xml
[INFO] run post-build script verify.groovy
[INFO]   java.io.FileNotFoundException: C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\jcl-without-impl\target\surefire-reports\org.ops4j.pax.logging.test.jcl.CommonsLoggingApiTest-output.txt (El sistema no puede encontrar la ruta especificada)
[INFO]           jcl-without-impl\pom.xml ......................... FAILED (1.3 s)
[INFO] Building: log4j1\pom.xml
[INFO] run post-build script verify.groovy
[INFO]   java.io.FileNotFoundException: C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\log4j1\target\surefire-reports\org.ops4j.pax.logging.test.log4j1.Log4j1NativeApiTest-output.txt (El sistema no puede encontrar la ruta especificada)
[INFO]           log4j1\pom.xml ................................... FAILED (1.3 s)
[INFO] Building: log4j2\pom.xml
[INFO] run post-build script verify.groovy
[INFO]   java.io.FileNotFoundException: C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\log4j2\target\surefire-reports\org.ops4j.pax.logging.test.log4j2.Log4j2NativeApiTest-output.txt (El sistema no puede encontrar la ruta especificada)
[INFO]           log4j2\pom.xml ................................... FAILED (1.4 s)
[INFO] Building: logback\pom.xml
[INFO]   The build exited with code 1. See C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\logback\build.log for details.
[INFO]           logback\pom.xml .................................. FAILED (1.3 s)
[INFO] Building: pax-logging-api-avalon\pom.xml
[INFO]   The build exited with code 1. See C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\pax-logging-api-avalon\build.log for details.
[INFO]           pax-logging-api-avalon\pom.xml ................... FAILED (1.2 s)
[INFO] Building: pax-logging-api-jboss-logging\pom.xml
[INFO] run post-build script verify.groovy
[INFO]   java.io.FileNotFoundException: C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\pax-logging-api-jboss-logging\target\surefire-reports\org.ops4j.pax.logging.test.jbosslogging.JBossLoggingPaxLoggingApiTest-output.txt (El sistema no puede encontrar la ruta especificada)
[INFO]           pax-logging-api-jboss-logging\pom.xml ............ FAILED (1.3 s)
[INFO] Building: pax-logging-api-jcl\pom.xml
[INFO]   The build exited with code 1. See C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\pax-logging-api-jcl\build.log for details.
[INFO]           pax-logging-api-jcl\pom.xml ...................... FAILED (1.2 s)
[INFO] Building: pax-logging-api-juli\pom.xml
[INFO]   The build exited with code 1. See C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\pax-logging-api-juli\build.log for details.
[INFO]           pax-logging-api-juli\pom.xml ..................... FAILED (1.2 s)
[INFO] Building: pax-logging-api-log4j1\pom.xml
[INFO] run post-build script verify.groovy
[INFO]   java.io.FileNotFoundException: C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\pax-logging-api-log4j1\target\surefire-reports\org.ops4j.pax.logging.test.log4j1.Log4j1PaxLoggingApiTest-output.txt (El sistema no puede encontrar la ruta especificada)
[INFO]           pax-logging-api-log4j1\pom.xml ................... FAILED (1.3 s)
[INFO] Building: pax-logging-api-log4j2\pom.xml
[INFO] run post-build script verify.groovy
[INFO]   java.io.FileNotFoundException: C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\pax-logging-api-log4j2\target\surefire-reports\org.ops4j.pax.logging.test.log4j2.Log4j2PaxLoggingApiTest-output.txt (El sistema no puede encontrar la ruta especificada)
[INFO]           pax-logging-api-log4j2\pom.xml ................... FAILED (1.2 s)
[INFO] Building: pax-logging-api-slf4j\pom.xml
[INFO]   The build exited with code 1. See C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\pax-logging-api-slf4j\build.log for details.
[INFO]           pax-logging-api-slf4j\pom.xml .................... FAILED (1.2 s)
[INFO] Building: slf4j-with-jcl-binder\pom.xml
[INFO] run post-build script verify.groovy
[INFO]   java.io.FileNotFoundException: C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\slf4j-with-jcl-binder\target\surefire-reports\org.ops4j.pax.logging.test.slf4j.Slf4JApiTest-output.txt (El sistema no puede encontrar la ruta especificada)
[INFO]           slf4j-with-jcl-binder\pom.xml .................... FAILED (1.2 s)
[INFO] Building: slf4j-with-nop-binder\pom.xml
[INFO] run post-build script verify.groovy
[INFO]   Assertion Error
[INFO]           slf4j-with-nop-binder\pom.xml .................... FAILED (1.3 s)
[INFO] Building: slf4j-with-simple-binder\pom.xml
[INFO] run post-build script verify.groovy
[INFO]   java.io.FileNotFoundException: C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\slf4j-with-simple-binder\target\surefire-reports\org.ops4j.pax.logging.test.slf4j.Slf4JApiTest-output.txt (El sistema no puede encontrar la ruta especificada)
[INFO]           slf4j-with-simple-binder\pom.xml ................. FAILED (1.2 s)
[INFO] Building: slf4j-without-binder\pom.xml
[INFO] run post-build script verify.groovy
[INFO]   java.io.FileNotFoundException: C:\eclipse\java\workspace\org.ops4j.pax.logging-logging-2.0.14\pax-logging-api-test\target\it\slf4j-without-binder\target\surefire-reports\org.ops4j.pax.logging.test.slf4j.Slf4JApiTest-output.txt (El sistema no puede encontrar la ruta especificada)
[INFO]           slf4j-without-binder\pom.xml ..................... FAILED (1.2 s)
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 16, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  jboss-logging\pom.xml
[ERROR] *  jcl-without-impl\pom.xml
[ERROR] *  log4j1\pom.xml
[ERROR] *  log4j2\pom.xml
[ERROR] *  logback\pom.xml
[ERROR] *  pax-logging-api-avalon\pom.xml
[ERROR] *  pax-logging-api-jboss-logging\pom.xml
[ERROR] *  pax-logging-api-jcl\pom.xml
[ERROR] *  pax-logging-api-juli\pom.xml
[ERROR] *  pax-logging-api-log4j1\pom.xml
[ERROR] *  pax-logging-api-log4j2\pom.xml
[ERROR] *  pax-logging-api-slf4j\pom.xml
[ERROR] *  slf4j-with-jcl-binder\pom.xml
[ERROR] *  slf4j-with-nop-binder\pom.xml
[ERROR] *  slf4j-with-simple-binder\pom.xml
[ERROR] *  slf4j-without-binder\pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for OPS4J Pax Logging (Build POM) 2.0.14:
[INFO]
[INFO] OPS4J Pax Logging (Build POM) ...................... SUCCESS [  0.417 s]
[INFO] OPS4J Pax Logging - API ............................ SUCCESS [  8.379 s]
[INFO] OPS4J Pax Logging - API tests ...................... FAILURE [ 22.711 s]
[INFO] OPS4J Pax Logging - Log4Jv1 implementation ......... SKIPPED
[INFO] OPS4J Pax Logging - Log4Jv2 implementation ......... SKIPPED
[INFO] OPS4J Pax Logging - Log4Jv2 extra packages ......... SKIPPED
[INFO] OPS4J Pax Logging - Logback implementation ......... SKIPPED
[INFO] OPS4J Pax Logging - Samples (Build POM) ............ SKIPPED
[INFO] OPS4J Pax Logging - Samples - Fragment ............. SKIPPED
[INFO] OPS4J Pax Logging - Samples - Fragment for Logback . SKIPPED
[INFO] OPS4J Pax Logging - Samples - Fragment for Log4J2 .. SKIPPED
[INFO] OPS4J Pax Logging - Samples - Fragment for Log4J2/H2 SKIPPED
[INFO] OPS4J Pax Logging - Integration Tests .............. SKIPPED
[INFO] OPS4J Pax Logging - Karaf .......................... SKIPPED
[INFO] OPS4J Pax Logging - Karaf KAR Logger ............... SKIPPED
[INFO] OPS4J Pax Logging - Karaf KAR ...................... SKIPPED
[INFO] OPS4J Pax Logging - Karaf Distribution ............. SKIPPED
[INFO] OPS4J Pax Logging - Karaf Integration Tests ........ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.198 s
[INFO] Finished at: 2022-01-04T14:00:19-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.2.2:run (integration-test) on project pax-logging-api-test: 16 builds failed. See console output above for details. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :pax-logging-api-test`

**Comment by melkorex** [comment]
Example, folder pax-logging-api-test\target\it\jboss-logging dont create /target folder

**Comment by grgrzybek** [comment]
Hmm, Windows and maven-invoker-plugin tests failing. Please check with `-DskipTests`. Why do you want to build it from source if it's in Maven Central?

**Comment by melkorex** [comment]
Build ok Thanks !
