### ISSUE TITLE
[1.10.x] Switch from log4j to reload4j

### ISSUE THREAD

**Issue by grgrzybek** [ops4j/org.ops4j.pax.logging#458]

**Comment by grgrzybek** [comment]
Fixed with 6170b33f (sorry, bad commit message)

**Comment by bertdewolf** [comment]
Could this be pulled in the jdk8 branch?

**Comment by grgrzybek** [comment]
ah sure - but without a release to Maven Central ;)

**Comment by grgrzybek** [comment]
Fixed here: https://github.com/ops4j/org.ops4j.pax.logging/commit/06ca3c6c86d8da16e6df78a4e6b03eec0c29e930
In special https://github.com/ops4j/org.ops4j.pax.logging/commits/pax-logging-1.10.x-jdk8 branch
