### ISSUE TITLE
Wrap log4j JsonTemplateLayout in pax-logging-log4j2

### ISSUE THREAD

**Issue by jbonofre** [ops4j/org.ops4j.pax.logging#459]
We just have to include a new log4j artifact in the wrapping (no additional dependency should be required).

**Comment by jbonofre** [comment]
Other additional log4j-* artifacts could be included this way.

**Comment by grgrzybek** [comment]
Thanks @svogt for the PR! I've added an integration test for this layout. Here's [properties-based configuration](https://github.com/ops4j/org.ops4j.pax.logging/blob/4a80962/pax-logging-it/src/test/resources/org/ops4j/pax/logging/it/log4j2-all.properties#L373-L383):
```
json.template.log4j2.appender.file.type = File
json.template.log4j2.appender.file.name = file
json.template.log4j2.appender.file.fileName = target/logs-log4j2/json-template.log
json.template.log4j2.appender.file.append = true
json.template.log4j2.appender.file.layout.type = JsonTemplateLayout
json.template.log4j2.appender.file.layout.eventTemplateUri = ${karaf.etc.uri}/logging-template.json

json.template.log4j2.rootLogger.level = info
json.template.log4j2.rootLogger.appenderRef.file.ref = file
```

**Comment by grgrzybek** [comment]
Backports:
* to 2.0.x: #472
* to 1.12.x: #473
* to 1.11.x: #474
