### ISSUE TITLE
[2.2.x] Update reload4j to 1.2.22

### ISSUE THREAD

**Issue by coheigea** [ops4j/org.ops4j.pax.logging#499]
Please update reload4j to 1.2.22. From https://reload4j.qos.ch/news.html

2022-07-21 - Release of reload4j 1.2.22
• Fixed a newly discovered [XXE vector vulnerability](https://github.com/qos-ch/reload4j/issues/53) reported against Chainsaw. This issue was reported by PJ Fanning.

**Comment by grgrzybek** [comment]
Thanks for report!

**Comment by coheigea** [comment]
Thanks for the fast response @grgrzybek !
