### ISSUE TITLE
Memory Leak when creating lots of non static loggers outside of an OSGI runtime

### ISSUE THREAD

**Issue by sarod** [ops4j/org.ops4j.pax.logging#53]
### Overview

When running code with pax-logging jar in the class path references to all loggers are kept in static property org.ops4j.pax.logging.internal.Activator.m_loggers until the Activator start.

They are cleared on Activator start but when running in non-OSGI mode (for test case for instance) or if bundle doesn't start this is never cleared causing a memory leak.

### Steps to reproduce
- Use the sample project [here:](https://github.com/sarod/bugs-repro/tree/master/pax-logging-memory-leak).
- Execute the unit test StressTest 
- Do a memory dump after some time. You'll see that instances of org.ops4j.pax.logging.slf4j.Slf4jLogger and the LinkedList used by m_loggers uses all the memory.

### Potential solution
- The m_loggers LinkedList should store WeakReferences to loggers instead of loggers directly
- LinkedList elements containing garbage collected items should be removed to reclaim the LinkedList memory. This could be done when adding new loggers.

**Comment by niclash** [comment]
Why is pax-logging outside OSGi environment? It was designed for OSGi use only...

**Comment by amergey** [comment]
An osgi application can have "regular" unit tests running outside osgi. When the code covered by unit test is using loggers then pax-logging can then run outside osgi in the context of the test.

**Comment by grgrzybek** [comment]
Hmm, something's wrong with the notifications... I didn't get an email about this one. Sorry!
I'm reviewing the pax-logging issues now.

**Comment by grgrzybek** [comment]
There was some memory-leak related discussion in this thread: https://groups.google.com/g/ops4j/c/yAB2hPuNgdM

https://ops4j1.jira.com/browse/PAXLOGGING-311 dealt with non-static loggers. Could you please check https://github.com/ops4j/org.ops4j.pax.logging/blob/master/pax-logging-it/src/test/java/org/ops4j/pax/logging/it/Log4J2MemoryIntegrationTest.java test to see if this scenario is similar to yours?

**Comment by grgrzybek** [comment]
@amergey can this be closed?

**Comment by grgrzybek** [comment]
@amergey you're creating 5M instances of `pax.logging.memory.leak.ClassUsingNonStaticSlf4JLogger` and each of these call:
```java
private final Logger logger = LoggerFactory.getLogger(getClass());
```

In OSGi environment, where a `org.ops4j.pax.logging.PaxLoggingManager` OSGi service is available it is used to obtain loggers and effectively use the underlying log manager. Outside of OSGi, a new instance of `org.ops4j.pax.logging.spi.support.DefaultServiceLog` is created every time.

Simply your example is too artificial and while interesting, I don't think we can do anything about it ;)

BTW, #374 fixed all the problems with non-static loggers and there's a linked discussion with great amount of details.
