### ISSUE TITLE
[2.x] Export org.apache.commons.logging 1.3.0 package (and update to commons-logging 1.3.0)

### ISSUE THREAD

**Issue by jbonofre** [ops4j/org.ops4j.pax.logging#542]

**Comment by grgrzybek** [comment]
I won't do it before my Christmas break. If you have time, I don't want to hold you, but I can also do it early January.

**Comment by jbonofre** [comment]
@grgrzybek no worries, I will do that (and release 😄 ). Enjoy Christmas break !
