### ISSUE TITLE
Parameters are not resolved in logged message

### ISSUE THREAD

**Issue by ghost** [ops4j/org.ops4j.pax.logging#56]
Using the OSGi R7 Logger facade like this `logger.info("test: {} {}","arg1","arg2")` with log4j2 as back-end result in the following log: `test {} {}` instead of the expected `test arg1 arg2`.

Note that it works with one parameter, but failed as soon as the called log method contains more than one arguments (including exception).

Maybe this is related to the fact that the args argument is actually not used in the doLog0 method: [link](https://github.com/ops4j/org.ops4j.pax.logging/blob/ef55fc8e2f004bf377e13df99afd888315b4ef22/pax-logging-log4j2/src/main/java/org/ops4j/pax/logging/log4j2/internal/PaxLoggerImpl.java#L1115)

**Comment by cdelg-ct** [comment]
I can confirm that changing
```java
    Message msg = originalMessage == null ? m_delegate.getMessageFactory().newMessage(message): originalMessage;
```
to
```java
Message msg = originalMessage == null ? m_delegate.getMessageFactory().newMessage(message, args): originalMessage;
```
fixes the issue. I can make a PR for this but it seems I am not allowed to push commit.

**Comment by laeubi** [comment]
1. Fork the repository
2. Check out your fork
3. create a branch and push your changes
4. now you can create a PR

**Comment by grgrzybek** [comment]
Hmm, something's wrong with the notifications... I didn't get an email about this one. Sorry!
I'm reviewing the pax-logging issues now.
